"use client";

import { useEffect, useMemo, useState } from "react";
import { Box, ChevronRight, GraduationCap, Headphones, Layers3, Menu, Minus, Plus, Printer, Search, ShieldCheck, ShoppingBag, Trash2, Truck, Wrench, X } from "lucide-react";

type Product={id:string;name:string;subtitle:string;price:number;category:"Filamentos"|"Impressoras 3D";image?:string;colors?:string[];href:string;featured?:boolean};
type Cart=Record<string,number>;

const products:Product[]=[
  {id:"k2-combo",name:"Creality K2 Combo",subtitle:"Impressora 3D com sistema multicolor Combo",price:1000,category:"Impressoras 3D",image:"/creality-k2-combo.png",href:"/nova-3d-lab/produtos/creality-k2-combo",featured:true},
  {id:"k2-pro-combo",name:"Creality K2 Pro Combo",subtitle:"Solução Combo para criação e produção profissional",price:1500,category:"Impressoras 3D",image:"/creality-k2-pro-combo.png",href:"/nova-3d-lab/produtos/creality-k2-pro-combo",featured:true},
  {id:"pla-1000g",name:"PLA",subtitle:"1000 g · Projetos visuais e prototipagem",price:20,category:"Filamentos",image:"/filament-pla-1000g.png",colors:["#151515","#f4f1eb","#c54b42","#315d89","#4d7550","#d8a940"],href:"/nova-3d-lab/produtos/pla-1000g"},
  {id:"petg-1000g",name:"PETG",subtitle:"1000 g · Peças funcionais e resistentes",price:22,category:"Filamentos",image:"/filament-petg-1000g.png",colors:["#151515","#f4f1eb","#315d89","#d77643"],href:"/nova-3d-lab/produtos/petg-1000g"},
  {id:"tpu-1000g",name:"TPU",subtitle:"1000 g · Proteções e peças flexíveis",price:50,category:"Filamentos",image:"/filament-tpu-1000g.png",colors:["#151515","#f4f1eb","#315d89"],href:"/nova-3d-lab/produtos/tpu-1000g"},
  {id:"petg-200g",name:"PETG",subtitle:"200 g · Testes e pequenos projetos",price:15,category:"Filamentos",image:"/filament-petg-200g.png",colors:["#151515","#f4f1eb","#4d7550","#d77643"],href:"/nova-3d-lab/produtos/petg-200g"},
];
const money=(n:number)=>`US$ ${n.toLocaleString("en-US")}`;

export default function Storefront(){
  const [cart,setCart]=useState<Cart>({}); const [cartOpen,setCartOpen]=useState(false); const [menuOpen,setMenuOpen]=useState(false);
  const [hydrated,setHydrated]=useState(false);
  const [category,setCategory]=useState("Todos"); const [query,setQuery]=useState(""); const [delivery,setDelivery]=useState("Levantamento na loja");
  useEffect(()=>{try{const saved=localStorage.getItem("nova-cart");if(saved)setCart(JSON.parse(saved));}catch{}finally{setHydrated(true)}},[]);
  useEffect(()=>{if(hydrated)localStorage.setItem("nova-cart",JSON.stringify(cart));},[cart,hydrated]);
  const shown=useMemo(()=>products.filter(p=>(category==="Todos"||p.category===category)&&(`${p.name} ${p.subtitle}`.toLowerCase().includes(query.toLowerCase()))),[category,query]);
  const count=Object.values(cart).reduce((a,b)=>a+b,0); const total=products.reduce((sum,p)=>sum+(cart[p.id]||0)*p.price,0);
  const change=(id:string,delta:number)=>setCart(current=>{const next={...current};const qty=(next[id]||0)+delta;if(qty<=0)delete next[id];else next[id]=qty;return next;});
  const orderLines=products.filter(p=>cart[p.id]).map(p=>`• ${p.name} — ${cart[p.id]} × ${money(p.price)} = ${money(cart[p.id]*p.price)}`);
  const checkout=`https://wa.me/244946459991?text=${encodeURIComponent(`Olá, gostaria de confirmar este pedido na NOVA LAB:\n\n${orderLines.join("\n")}\n\nSubtotal dos produtos: ${money(total)}\nEntrega: ${delivery}\n\nPor favor, confirmem o stock, as cores disponíveis, o valor final e o prazo.`)}`;
  return <main className="shop-page">
    <div className="shop-notice">LEVANTAMENTO EM CAMAMA · ENTREGA EM LUANDA SOB CONSULTA · WHATSAPP +244 946 459 991</div>
    <header className="shop-header"><a className="shop-logo" href="/"><img src="/nova-lab-logo-transparent.png" alt="NOVA LAB"/></a><label className="header-search"><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="O que procura?" aria-label="Pesquisar produtos"/></label><nav className={menuOpen?"shop-nav open":"shop-nav"}><a href="#loja">LOJA</a><a href="#servicos">SERVIÇOS</a><a href="/sobre-nos">SOBRE NÓS</a><a href="/contacto">CONTACTO</a></nav><div className="shop-header-actions"><button className="shop-menu-button" onClick={()=>setMenuOpen(!menuOpen)} aria-label="Abrir menu"><Menu/></button><button className="cart-button" onClick={()=>setCartOpen(true)}><ShoppingBag/><span>CARRINHO</span><b>{count}</b></button></div></header>
    <nav className="category-bar" aria-label="Categorias"><a href="#loja" onClick={()=>setCategory("Filamentos")}><Layers3/> FILAMENTOS</a><a href="#loja" onClick={()=>setCategory("Impressoras 3D")}><Printer/> IMPRESSORAS 3D</a><a href="#servicos"><Wrench/> PEÇAS E SUPORTE</a><a href="#servicos"><Box/> IMPRESSÃO POR ENCOMENDA</a><a href="#servicos"><GraduationCap/> FORMAÇÃO</a></nav>
    <section className="commerce-hero"><div className="commerce-hero-copy"><p>NOVA 3D LAB · LOJA EM LUANDA</p><h1>Crie mais.<br/><span>Nós fornecemos as ferramentas.</span></h1><p>Impressoras 3D, filamentos e apoio local para transformar ideias em objetos reais.</p><div><a href="#loja">COMPRAR AGORA <ChevronRight/></a><a href="/nova-3d-lab">CONHECER OS SERVIÇOS</a></div></div><div className="commerce-hero-product"><img src="/creality-k2-pro-combo.png" alt="Creality K2 Pro Combo"/><div><span>DESTAQUE</span><b>Creality K2 Pro Combo</b><strong>US$ 1,500</strong></div></div></section>
    <section className="shop-benefits"><div><Truck/><b>ENTREGA EM LUANDA</b><span>Prazo e custo confirmados antes do pagamento</span></div><div><Headphones/><b>APOIO LOCAL</b><span>Orientação antes e depois da compra</span></div><div><ShieldCheck/><b>COMPRA TRANSPARENTE</b><span>Preço, stock e condições confirmados por escrito</span></div><div><Box/><b>LEVANTAMENTO</b><span>Shopping Popular · Camama</span></div></section>
    <section className="store-section" id="loja"><div className="store-heading"><div><p>CATÁLOGO NOVA LAB</p><h2>Produtos para começar e produzir.</h2></div><span>{shown.length} produtos</span></div><div className="store-tools"><div className="category-tabs">{["Todos","Impressoras 3D","Filamentos"].map(item=><button className={category===item?"active":""} key={item} onClick={()=>setCategory(item)}>{item}</button>)}</div><label className="product-search"><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Pesquisar produtos" aria-label="Pesquisar produtos"/></label></div><div className="commerce-grid">{shown.map(product=><article className={product.featured?"commerce-card featured":"commerce-card"} key={product.id}><a className="commerce-image" href={product.href}>{product.image?<img src={product.image} alt={product.name}/>:<div className="shop-spool"><span>{product.name}</span><i/></div>}</a><div className="commerce-info"><p>{product.category}</p><a href={product.href}><h3>{product.name}</h3></a><span>{product.subtitle}</span>{product.colors&&<div className="commerce-colors">{product.colors.map(c=><i key={c} style={{backgroundColor:c}}/>)}</div>}<div className="commerce-price"><strong>{money(product.price)}</strong><small>Stock a confirmar</small></div><div className="commerce-actions"><a href={product.href}>DETALHES</a><button onClick={()=>{change(product.id,1);setCartOpen(true)}}><Plus/> ADICIONAR</button></div></div></article>)}</div>{shown.length===0&&<div className="empty-products">Nenhum produto encontrado.</div>}</section>
    <section className="services-market" id="servicos"><div className="section-intro"><p>SOLUÇÕES NOVA 3D LAB</p><h2>Da primeira ideia à produção.</h2><span>Uma equipa local para orientar, criar, imprimir e manter a sua operação.</span></div><div className="service-market-grid"><article><Printer/><h3>Escolha a sua impressora</h3><p>Equipamentos para iniciação, escolas, criadores e produção profissional.</p><a href="#loja" onClick={()=>setCategory("Impressoras 3D")}>VER IMPRESSORAS →</a></article><article><Box/><h3>Impressão por encomenda</h3><p>Envie o ficheiro ou explique a ideia. Analisamos material, acabamento, prazo e preço.</p><a href="https://wa.me/244946459991?text=Olá%2C%20gostaria%20de%20pedir%20um%20orçamento%20para%20impressão%203D.">PEDIR ORÇAMENTO →</a></article><article><Wrench/><h3>Modelação e suporte</h3><p>Desenho 3D, preparação de ficheiros, instalação, peças e assistência técnica.</p><a href="/nova-3d-lab">CONHECER SERVIÇOS →</a></article><article><GraduationCap/><h3>Formação básica</h3><p>Aprenda filamento, preparação, operação e cuidados essenciais da impressora.</p><a href="https://wa.me/244946459991?text=Olá%2C%20gostaria%20de%20informações%20sobre%20a%20formação%20em%20impressão%203D.">CONSULTAR TURMAS →</a></article></div></section>
    <section className="work-showcase"><div className="section-intro"><p>POSSIBILIDADES REAIS</p><h2>O que podemos criar.</h2><span>Arquitetura, peças decorativas, modelos, personagens e produtos personalizados.</span></div><div className="work-grid"><figure className="wide"><img src="/work-villa.png" alt="Maquete arquitetónica produzida em 3D"/><figcaption>MAQUETES DE ARQUITETURA</figcaption></figure><figure><img src="/work-dragon.png" alt="Escultura de dragão impressa em 3D"/><figcaption>ARTE E COLECIONÁVEIS</figcaption></figure><figure><img src="/work-aircraft.png" alt="Modelo de avião produzido em 3D"/><figcaption>MODELOS TÉCNICOS</figcaption></figure><figure><img src="/work-lamp.png" alt="Candeeiro personalizado com elementos impressos em 3D"/><figcaption>DECORAÇÃO FUNCIONAL</figcaption></figure><figure><img src="/work-vase.png" alt="Vaso artístico impresso em 3D"/><figcaption>OBJETOS DECORATIVOS</figcaption></figure><figure><img src="/work-figure.png" alt="Figura colecionável produzida em 3D"/><figcaption>PERSONAGENS</figcaption></figure></div></section>
    <section className="shop-service-strip"><div><p>JÁ TEM UM MODELO OU APENAS UMA IDEIA?</p><h2>Transformamos o seu projeto numa peça real.</h2></div><a href="https://wa.me/244946459991?text=Olá%2C%20gostaria%20de%20pedir%20um%20orçamento%20para%20impressão%203D." target="_blank" rel="noreferrer">ENVIAR PROJETO →</a></section>
    <section className="buyer-guide"><div><p>COMPRE COM ORIENTAÇÃO</p><h2>Não sabe por onde começar?</h2></div><div><b>01</b><h3>Diga-nos o que deseja criar</h3><p>Uso pessoal, educação, protótipo, manutenção ou produção.</p></div><div><b>02</b><h3>Receba uma recomendação</h3><p>Indicamos impressora, material e serviço adequados ao objetivo.</p></div><div><b>03</b><h3>Confirme e levante</h3><p>Validamos stock, pagamento, entrega e apoio inicial por WhatsApp.</p></div></section>
    <footer className="shop-footer"><div><img src="/nova-lab-logo-transparent.png" alt="NOVA LAB"/><p>Impressoras 3D, materiais, serviços e formação para criadores em Angola.</p></div><div><b>LOJA</b><a href="#loja">Todos os produtos</a><a href="/nova-3d-lab/filamentos">Filamentos</a><a href="/nova-3d-lab">Serviços 3D</a></div><div><b>ATENDIMENTO</b><span>Camama Shopping Popular<br/>Bloco 11 · Lojas B03–04<br/>Luanda, Angola</span><a href="https://wa.me/244946459991">WhatsApp +244 946 459 991</a></div><div><b>INFORMAÇÕES</b><a href="/contacto">Entrega e levantamento</a><a href="/contacto">Pagamento e encomendas</a><a href="/contacto">Garantia e devoluções</a></div></footer>
    {cartOpen&&<><button className="cart-backdrop" aria-label="Fechar carrinho" onClick={()=>setCartOpen(false)}/><aside className="cart-drawer" aria-label="Carrinho de compras"><div className="cart-title"><div><span>SEU PEDIDO</span><h2>Carrinho</h2></div><button onClick={()=>setCartOpen(false)} aria-label="Fechar"><X/></button></div><div className="cart-items">{count===0?<div className="empty-cart"><ShoppingBag/><h3>O carrinho está vazio.</h3><p>Escolha um produto para começar.</p><button onClick={()=>setCartOpen(false)}>VER PRODUTOS</button></div>:products.filter(p=>cart[p.id]).map(p=><article key={p.id}>{p.image?<img src={p.image} alt=""/>:<div className="cart-spool">{p.name}</div>}<div><h3>{p.name}</h3><span>{p.subtitle.split("·")[0]}</span><strong>{money(p.price)}</strong><div className="qty"><button onClick={()=>change(p.id,-1)}><Minus/></button><b>{cart[p.id]}</b><button onClick={()=>change(p.id,1)}><Plus/></button><button className="remove" onClick={()=>setCart(c=>{const n={...c};delete n[p.id];return n})}><Trash2/></button></div></div></article>)}</div>{count>0&&<div className="cart-summary"><label>ENTREGA<select value={delivery} onChange={e=>setDelivery(e.target.value)}><option>Levantamento na loja</option><option>Entrega em Luanda — calcular</option><option>Outra localidade — consultar</option></select></label><div><span>SUBTOTAL</span><strong>{money(total)}</strong></div><p>A entrega não está incluída. Stock, cores, valor final e pagamento serão confirmados por escrito.</p><a href={checkout} target="_blank" rel="noreferrer">FINALIZAR PELO WHATSAPP</a></div>}</aside></>}
  </main>;
}
